# Generated by Django 3.2 on 2022-08-09 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FontListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_name', models.CharField(default='Prompt.ttf', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HuayListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(default='None', max_length=255)),
                ('full_name', models.CharField(default='None', max_length=255)),
                ('page_name', models.CharField(default='None', max_length=255)),
                ('time', models.TimeField()),
                ('link', models.CharField(default='None', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(default='None', max_length=255)),
                ('usertype', models.CharField(default='random', max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('credit_shop', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HuayTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_text', models.CharField(default='None', max_length=255)),
                ('font_number', models.CharField(default='None', max_length=255)),
                ('text_color', models.CharField(default='None', max_length=255)),
                ('border_size', models.IntegerField(default=0)),
                ('border_color', models.CharField(default='None', max_length=255)),
                ('text_pos_x', models.IntegerField(default=0)),
                ('text_pos_y', models.IntegerField(default=0)),
                ('text_font_size', models.IntegerField(default=0)),
                ('date_pos_x', models.IntegerField(default=0)),
                ('date_pos_y', models.IntegerField(default=0)),
                ('date_font_size', models.IntegerField(default=0)),
                ('main_num_pos_x', models.IntegerField(default=0)),
                ('main_num_pos_y', models.IntegerField(default=0)),
                ('main_num_font_size', models.IntegerField(default=0)),
                ('focus_num_pos_x', models.IntegerField(default=0)),
                ('focus_num_pos_y', models.IntegerField(default=0)),
                ('focus_num_font_size', models.IntegerField(default=0)),
                ('row1_x', models.IntegerField(default=0)),
                ('row1_y', models.IntegerField(default=0)),
                ('row2_x', models.IntegerField(default=0)),
                ('row2_y', models.IntegerField(default=0)),
                ('row_font_size', models.IntegerField(default=0)),
                ('credit_shop_pos_x', models.IntegerField(default=0)),
                ('credit_shop_pos_y', models.IntegerField(default=0)),
                ('credit_shop_font_size', models.IntegerField(default=0)),
                ('huay_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huayrandom.huaylistmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
