# Generated by Django 4.0.6 on 2022-07-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0003_alter_huaytypemodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huaytypemodel',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
