# Generated by Django 3.2 on 2022-07-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0004_alter_huaytypemodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='house_name',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
