# Generated by Django 3.2 on 2022-08-05 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0005_profilemodel_house_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuayListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(default='None', max_length=255)),
                ('full_name', models.CharField(default='None', max_length=255)),
                ('page_name', models.CharField(default='None', max_length=255)),
                ('time', models.DateTimeField()),
                ('link', models.CharField(default='None', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='huaytypemodel',
            name='link',
        ),
        migrations.RemoveField(
            model_name='huaytypemodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='huaytypemodel',
            name='page_name',
        ),
        migrations.RemoveField(
            model_name='huaytypemodel',
            name='time',
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='huay_list',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='huayrandom.huaylistmodel'),
        ),
    ]
