# Generated by Django 3.2 on 2022-08-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0007_alter_huaytypemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huaylistmodel',
            name='time',
            field=models.TimeField(),
        ),
    ]
