# Generated by Django 3.2 on 2022-08-10 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0010_fontlistmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huaytypemodel',
            name='huay_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huayrandom.huaylistmodel'),
        ),
    ]
