# Generated by Django 3.2 on 2022-08-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0011_profilemodel_credit_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='credit_shop',
            field=models.BooleanField(default=True),
        ),
    ]
