# Generated by Django 3.2 on 2022-08-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0013_auto_20220810_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(default='None', max_length=255)),
                ('color_code', models.CharField(default='255,255,255', max_length=255)),
            ],
        ),
    ]
