# Generated by Django 3.2 on 2022-08-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0014_colorlistmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='random_mode',
            field=models.CharField(default='random_any', max_length=255),
        ),
    ]
