# Generated by Django 3.2 on 2022-08-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0015_profilemodel_random_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='huaytypemodel',
            name='color_list',
            field=models.ManyToManyField(to='huayrandom.ColorListModel'),
        ),
    ]
