# Generated by Django 3.2 on 2022-08-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0016_huaytypemodel_color_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huaytypemodel',
            name='color_list',
            field=models.ManyToManyField(default=1, to='huayrandom.ColorListModel'),
        ),
    ]
