# Generated by Django 3.2 on 2022-08-11 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0017_alter_huaytypemodel_color_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huaytypemodel',
            name='color_list',
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='color_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='huayrandom.colorlistmodel'),
        ),
    ]
