# Generated by Django 3.2 on 2022-08-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0018_auto_20220811_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huaytypemodel',
            name='color_list',
        ),
        migrations.AlterField(
            model_name='huaytypemodel',
            name='border_color',
            field=models.CharField(default=2, max_length=255),
        ),
        migrations.AlterField(
            model_name='huaytypemodel',
            name='text_color',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
