# Generated by Django 3.2 on 2022-08-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0019_auto_20220811_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huaytypemodel',
            name='border_color',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='huaytypemodel',
            name='text_color',
            field=models.IntegerField(default=1),
        ),
    ]
