# Generated by Django 3.2 on 2022-08-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0020_auto_20220811_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='huaytypemodel',
            name='row_1_separator',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='row_2_separator',
            field=models.CharField(default='', max_length=255),
        ),
    ]
