# Generated by Django 3.2 on 2022-08-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0021_auto_20220811_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='huaytypemodel',
            name='main_num_separator',
            field=models.CharField(default=' - ', max_length=255),
        ),
        migrations.AlterField(
            model_name='huaytypemodel',
            name='row_1_separator',
            field=models.CharField(default=' - ', max_length=255),
        ),
        migrations.AlterField(
            model_name='huaytypemodel',
            name='row_2_separator',
            field=models.CharField(default=' - ', max_length=255),
        ),
    ]
