# Generated by Django 3.2 on 2022-08-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0022_auto_20220811_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='huaytypemodel',
            name='border_status',
            field=models.CharField(default='on', max_length=25),
        ),
    ]
