# Generated by Django 3.2 on 2022-08-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0023_huaytypemodel_border_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='huaytypemodel',
            name='focus_num_color',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='main_num_color',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='row_1_color',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='row_2_color',
            field=models.IntegerField(default=1),
        ),
    ]
