# Generated by Django 3.2 on 2022-08-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0024_auto_20220812_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='huaytypemodel',
            name='date_color',
            field=models.IntegerField(default=1),
        ),
    ]
