# Generated by Django 3.2 on 2022-08-12 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0025_huaytypemodel_date_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huaytypemodel',
            old_name='row_1_color',
            new_name='row1_color',
        ),
        migrations.RenameField(
            model_name='huaytypemodel',
            old_name='row_1_separator',
            new_name='row1_separator',
        ),
        migrations.RenameField(
            model_name='huaytypemodel',
            old_name='row_2_color',
            new_name='row2_color',
        ),
        migrations.RenameField(
            model_name='huaytypemodel',
            old_name='row_2_separator',
            new_name='row2_separator',
        ),
    ]
