# Generated by Django 3.2 on 2022-08-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0027_auto_20220812_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huaytypemodel',
            name='credit_shop_border_status',
            field=models.CharField(default='off', max_length=25),
        ),
        migrations.AlterField(
            model_name='huaytypemodel',
            name='focus_num_border_status',
            field=models.CharField(default='off', max_length=25),
        ),
        migrations.AlterField(
            model_name='huaytypemodel',
            name='main_num_border_status',
            field=models.CharField(default='off', max_length=25),
        ),
        migrations.AlterField(
            model_name='huaytypemodel',
            name='row1_border_status',
            field=models.CharField(default='off', max_length=25),
        ),
        migrations.AlterField(
            model_name='huaytypemodel',
            name='row2_border_status',
            field=models.CharField(default='off', max_length=25),
        ),
        migrations.AlterField(
            model_name='huaytypemodel',
            name='text_border_status',
            field=models.CharField(default='off', max_length=25),
        ),
    ]
