# Generated by Django 3.2 on 2022-08-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0028_auto_20220812_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='huaytypemodel',
            name='three_main_border_color',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='three_main_border_size',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='three_main_border_status',
            field=models.CharField(default='off', max_length=25),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='three_main_font',
            field=models.CharField(default='HelveticaNeue.ttf', max_length=255),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='three_main_font_color',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='three_main_font_size',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='three_main_separator',
            field=models.CharField(default=' - ', max_length=25),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='three_main_status',
            field=models.CharField(default='off', max_length=255),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='three_sub_border_color',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='three_sub_border_size',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='three_sub_border_status',
            field=models.CharField(default='off', max_length=25),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='three_sub_font',
            field=models.CharField(default='HelveticaNeue.ttf', max_length=255),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='three_sub_font_color',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='three_sub_font_size',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='three_sub_separator',
            field=models.CharField(default=' - ', max_length=25),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='three_sub_status',
            field=models.CharField(default='off', max_length=25),
        ),
        migrations.AlterField(
            model_name='huaytypemodel',
            name='row1_separator',
            field=models.CharField(default=' - ', max_length=25),
        ),
        migrations.AlterField(
            model_name='huaytypemodel',
            name='row2_separator',
            field=models.CharField(default=' - ', max_length=25),
        ),
    ]
