# Generated by Django 3.2 on 2022-08-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0029_auto_20220814_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='huaytypemodel',
            name='three_main_pos_x',
            field=models.IntegerField(default=170),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='three_main_pos_y',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='three_sub_pos_x',
            field=models.IntegerField(default=170),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='three_sub_pos_y',
            field=models.IntegerField(default=1000),
        ),
    ]
