# Generated by Django 3.2 on 2022-08-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0030_auto_20220814_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huaytypemodel',
            name='row1_separator',
            field=models.CharField(blank=True, default=' - ', max_length=25),
        ),
        migrations.AlterField(
            model_name='huaytypemodel',
            name='row2_separator',
            field=models.CharField(blank=True, default=' - ', max_length=25),
        ),
    ]
