# Generated by Django 3.2 on 2022-08-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0031_auto_20220814_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huaytypemodel',
            old_name='font_number',
            new_name='main_num_font',
        ),
        migrations.RenameField(
            model_name='huaytypemodel',
            old_name='font_text',
            new_name='text_font',
        ),
    ]
