# Generated by Django 3.2 on 2022-08-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0032_auto_20220814_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huaytypemodel',
            old_name='main_num_color',
            new_name='main_num_font_color',
        ),
    ]
