# Generated by Django 3.2 on 2022-08-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0033_rename_main_num_color_huaytypemodel_main_num_font_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='huaytypemodel',
            name='row_font',
            field=models.CharField(default='HelveticaNeue.ttf', max_length=255),
        ),
    ]
