# Generated by Django 3.2 on 2022-08-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0034_huaytypemodel_row_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='huaytypemodel',
            name='remark_border_color',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='remark_border_size',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='remark_border_status',
            field=models.CharField(default='off', max_length=25),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='remark_font',
            field=models.CharField(default='supermarket.ttf', max_length=255),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='remark_font_color',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='remark_font_size',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='remark_pos_x',
            field=models.IntegerField(default=170),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='remark_pos_y',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='remark_status',
            field=models.CharField(default='off', max_length=25),
        ),
    ]
