# Generated by Django 3.2 on 2022-08-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0035_auto_20220814_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='huaytypemodel',
            name='remark_text',
            field=models.CharField(default='supermarket', max_length=255),
        ),
    ]
