# Generated by Django 3.2 on 2022-08-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0036_huaytypemodel_remark_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huaytypemodel',
            name='remark_pos_y',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='huaytypemodel',
            name='remark_text',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='huaytypemodel',
            name='three_main_pos_y',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='huaytypemodel',
            name='three_sub_pos_y',
            field=models.IntegerField(default=200),
        ),
    ]
