# Generated by Django 3.2 on 2022-08-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0037_auto_20220814_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='huaytypemodel',
            name='date_border_color',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='date_border_size',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='date_border_status',
            field=models.CharField(default='off', max_length=25),
        ),
    ]
