# Generated by Django 3.2 on 2022-08-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0038_auto_20220815_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='huaytypemodel',
            name='date_font',
            field=models.CharField(default='supermarket.ttf', max_length=255),
        ),
    ]
