# Generated by Django 3.2 on 2022-08-15 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0039_huaytypemodel_date_font'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huaytypemodel',
            old_name='date_color',
            new_name='date_font_color',
        ),
    ]
