# Generated by Django 3.2 on 2022-08-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0040_rename_date_color_huaytypemodel_date_font_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huaytypemodel',
            old_name='focus_num_color',
            new_name='focus_num_font_color',
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='focus_num_font',
            field=models.IntegerField(default=230),
        ),
    ]
