# Generated by Django 3.2 on 2022-08-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0041_auto_20220815_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huaytypemodel',
            name='focus_num_font',
            field=models.CharField(default='HelveticaNeue.ttf', max_length=255),
        ),
    ]
