# Generated by Django 3.2 on 2022-08-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0043_imagehousemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagehousemodel',
            old_name='loocation',
            new_name='location',
        ),
    ]
