# Generated by Django 3.2 on 2022-08-19 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0044_rename_loocation_imagehousemodel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='huaytypemodel',
            name='image_house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='huayrandom.imagehousemodel'),
        ),
    ]
