# Generated by Django 3.2 on 2022-08-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0045_huaytypemodel_image_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='huaylistmodel',
            name='order_number',
            field=models.IntegerField(default=1),
        ),
    ]
