# Generated by Django 4.0.6 on 2022-07-28 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('huayrandom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='verified_token',
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='usertype',
            field=models.CharField(default='random', max_length=255),
        ),
        migrations.CreateModel(
            name='HuayTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=255)),
                ('time', models.BooleanField(default=True)),
                ('link', models.CharField(default='None', max_length=255)),
                ('page_name', models.CharField(default='None', max_length=255)),
                ('font_text', models.CharField(default='None', max_length=255)),
                ('font_number', models.CharField(default='None', max_length=255)),
                ('text_color', models.CharField(default='None', max_length=255)),
                ('border_size', models.IntegerField(default=0)),
                ('border_color', models.CharField(default='None', max_length=255)),
                ('text_pos_x', models.IntegerField(default=0)),
                ('text_pos_y', models.IntegerField(default=0)),
                ('text_font_size', models.IntegerField(default=0)),
                ('data_pos_x', models.IntegerField(default=0)),
                ('data_pos_y', models.IntegerField(default=0)),
                ('data_font_size', models.IntegerField(default=0)),
                ('main_num_pos_x', models.IntegerField(default=0)),
                ('main_num_pos_y', models.IntegerField(default=0)),
                ('main_num_font_size', models.IntegerField(default=0)),
                ('focus_num_pos_x', models.IntegerField(default=0)),
                ('focus_num_pos_y', models.IntegerField(default=0)),
                ('focus_num_font_size', models.IntegerField(default=0)),
                ('row1_x', models.IntegerField(default=0)),
                ('row1_y', models.IntegerField(default=0)),
                ('row2_x', models.IntegerField(default=0)),
                ('row2_y', models.IntegerField(default=0)),
                ('row_font_size', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
