# Generated by Django 4.0.6 on 2022-07-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0002_remove_profilemodel_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huaytypemodel',
            name='time',
            field=models.DateTimeField(default=True),
        ),
    ]
