# Generated by Django 3.2 on 2022-08-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0008_alter_huaylistmodel_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huaytypemodel',
            old_name='data_font_size',
            new_name='date_font_size',
        ),
        migrations.RenameField(
            model_name='huaytypemodel',
            old_name='data_pos_x',
            new_name='date_pos_x',
        ),
        migrations.RenameField(
            model_name='huaytypemodel',
            old_name='data_pos_y',
            new_name='date_pos_y',
        ),
    ]
