# Generated by Django 3.2 on 2022-08-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0009_auto_20220806_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='FontListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_name', models.CharField(default='Prompt.ttf', max_length=255)),
            ],
        ),
    ]
