# Generated by Django 3.2 on 2022-08-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0011_alter_huaytypemodel_huay_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='credit_shop',
            field=models.BooleanField(default=True),
        ),
    ]
