# Generated by Django 3.2 on 2022-08-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayrandom', '0012_profilemodel_credit_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='huaytypemodel',
            name='credit_shop_font_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='credit_shop_pos_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='huaytypemodel',
            name='credit_shop_pos_y',
            field=models.IntegerField(default=0),
        ),
    ]
